In [ ]:
import pandas as pd

from parquet_files import COMPOSITE_DATA

composite_data = pd.read_parquet(COMPOSITE_DATA)

composite_data.head()

,ticker,custom_sentiment,finbert_sentiment,date,on_volatile_date,adjacent_volatile_date,very_near_volatile_date,near_volatile_date,p-7,p-6,...,p-2,p-1,p+0,p+1,p+2,p+3,p+4,p+5,p+6,p+7
0,GME,-1.320963,-1.622274,2021-01-28,False,False,False,False,NaN,9.780000,...,36.994999,86.877502,48.400002,81.250000,56.25,22.500000,23.102501,13.375000,15.942500,15.000000
1,GME,-0.032856,0.572957,2021-01-28,False,False,False,False,NaN,9.780000,...,36.994999,86.877502,48.400002,81.250000,56.25,22.500000,23.102501,13.375000,15.942500,15.000000
2,GME,-0.462225,0.609483,2021-01-28,False,False,False,False,NaN,9.780000,...,36.994999,86.877502,48.400002,81.250000,56.25,22.500000,23.102501,13.375000,15.942500,15.000000
3,GME,-0.462225,0.514058,2021-01-28,False,False,False,False,NaN,9.780000,...,36.994999,86.877502,48.400002,81.250000,56.25,22.500000,23.102501,13.375000,15.942500,15.000000
4,AMC,-0.462225,0.514058,2021-01-28,False,False,False,False,NaN,29.700001,...,49.599998,199.000000,86.300003,132.600006,133.00,78.199997,89.699997,70.900002,68.300003,61.799999

In [2]:
avg_cols = ['custom_sentiment', 'finbert_sentiment']

static_cols = [
  'on_volatile_date',
  'adjacent_volatile_date',
  'very_near_volatile_date',
  'near_volatile_date',
  'p-7',
  'p-6',
  'p-5',
  'p-4',
  'p-3',
  'p-2',
  'p-1',
  'p+0',
  'p+1',
  'p+2',
  'p+3',
  'p+4',
  'p+5',
  'p+6',
  'p+7',
]

df_avg = (
    composite_data
    .groupby(['ticker', 'date'])
    .agg(
        {**{c: 'mean' for c in avg_cols},
         **{c: 'first' for c in static_cols}}
    )
    .reset_index()
)

print(len(df_avg))
(df_avg.head())

6564

,ticker,date,custom_sentiment,finbert_sentiment,on_volatile_date,adjacent_volatile_date,very_near_volatile_date,near_volatile_date,p-7,p-6,...,p-2,p-1,p+0,p+1,p+2,p+3,p+4,p+5,p+6,p+7
0,AAL,2021-01-28,-0.137189,-0.080130,True,True,True,True,NaN,NaN,...,15.530000,16.559999,18.10,17.17,16.840000,16.59,17.600000,17.400000,17.190001,17.770000
1,AAL,2021-01-29,0.825882,-0.641556,False,True,True,True,NaN,15.83,...,16.559999,18.100000,17.17,16.84,16.590000,17.60,17.400000,17.190001,17.770000,17.440001
2,AAL,2021-01-31,0.396513,0.260556,False,False,True,True,NaN,15.83,...,16.559999,18.100000,17.17,16.84,16.590000,17.60,17.400000,17.190001,17.770000,17.440001
3,AAL,2021-02-01,-0.462225,0.611955,False,False,False,True,15.83,15.82,...,18.100000,17.170000,16.84,16.59,17.600000,17.40,17.190001,17.770000,17.440001,17.410000
4,AAL,2021-02-03,1.255251,0.727063,False,False,False,True,15.43,15.53,...,16.840000,16.590000,17.60,17.40,17.190001,17.77,17.440001,17.410000,16.990000,17.270000

In [ ]:
from parquet_files import AGGREGATE_DATA


df_avg.to_parquet(AGGREGATE_DATA, engine='pyarrow', compression='gzip')