In [1]:
import pandas as pd

df = pd.read_csv('../data/raw/reddit_wsb.csv')

In [2]:
df = df.drop('score', axis=1).drop('url', axis=1).drop('comms_num', axis=1).drop('id', axis=1).drop('timestamp', axis=1)
df['eastern'] = pd.to_datetime(df['created'], unit='s').dt.tz_localize('Asia/Shanghai').dt.tz_convert('US/Eastern')
df = df.drop('created', axis=1)
df['body'] = df['body'].fillna('')
df['text'] = df['title'] + '\n' + df['body']
df = df.drop("title", axis=1).drop("body", axis=1)

In [3]:
import re

# Removes URLs, reddit user mentions, and goofy whitespace stuff
def clean_text(text):
  text = re.sub(r'http\S+|www\S+', '', text)
  text = re.sub(r'u/\w+', '', text)
  text = re.sub(r'\s+', ' ', text)
  return text.strip()

In [4]:
df['text'] = df['text'].apply(clean_text)
df = df[df['text'].str.strip().astype(bool)]

In [5]:
print("Earliest:", df['eastern'].min())
print("Latest:", df['eastern'].max())

Earliest: 2020-09-28 12:46:56-04:00
Latest: 2021-08-15 18:26:20-04:00

In [6]:
df.head()

                    eastern                                               text
0 2021-01-28 06:37:41-05:00  It's not about the money, it's about sending a...
1 2021-01-28 06:32:10-05:00  Math Professor Scott Steiner says the numbers ...
2 2021-01-28 06:30:35-05:00  Exit the system The CEO of NASDAQ pushed to ha...
3 2021-01-28 06:28:57-05:00  NEW SEC FILING FOR GME! CAN SOMEONE LESS RETAR...
4 2021-01-28 06:26:56-05:00  Not to distract from GME, just thought our AMC...

In [7]:
from pytickersymbols import PyTickerSymbols

pts = PyTickerSymbols()

spy_5_tickers = pts.get_sp_500_nyc_yahoo_tickers()
spy_6_tickers = pts.get_sp_600_nyc_yahoo_tickers()
dow_tickers = pts.get_dow_jones_nyc_yahoo_tickers()
nasdaq_tickers = pts.get_nasdaq_100_nyc_yahoo_tickers()

unique_tickers = set(spy_5_tickers + spy_6_tickers + dow_tickers + nasdaq_tickers)
unique_tickers = {t for t in unique_tickers if not t[0].isdigit()}

ordered_tickers = sorted(unique_tickers)

print(ordered_tickers)
print(len(ordered_tickers))

['A', 'AAL', 'AAP', 'AAPL', 'ABBV', 'ABC', 'ABMD', 'ABNB', 'ABT', 'ACGL', 'ACN', 'ADBE', 'ADI', 'ADM', 'ADP', 'ADSK', 'ADTN', 'AEE', 'AEP', 'AES', 'AFL', 'AIG', 'AIZ', 'AJG', 'AKAM', 'ALB', 'ALGN', 'ALK', 'ALL', 'ALLE', 'AMAT', 'AMCCF', 'AMCR', 'AMD', 'AME', 'AMGN', 'AMP', 'AMT', 'AMZN', 'ANET', 'ANSS', 'AON', 'AOS', 'APA', 'APD', 'APH', 'APTV', 'ARE', 'ASML', 'ASMLF', 'ATO', 'ATVI', 'AVB', 'AVGO', 'AVY', 'AWK', 'AXP', 'AZN', 'AZNCF', 'AZO', 'BA', 'BAC', 'BAIDF', 'BALL', 'BALY', 'BAX', 'BBWI', 'BBY', 'BDX', 'BEN', 'BF-B', 'BIDU', 'BIIB', 'BIO', 'BK', 'BKNG', 'BKR', 'BLK', 'BLL', 'BMY', 'BMYMP', 'BOAPL', 'BR', 'BRK-B', 'BRO', 'BSX', 'BWA', 'BXP', 'C', 'CAG', 'CAH', 'CARR', 'CAT', 'CB', 'CBRE', 'CCI', 'CCL', 'CDAY', 'CDNS', 'CDW', 'CE', 'CEG', 'CF', 'CFG', 'CHD', 'CHRW', 'CHTR', 'CI', 'CINF', 'CL', 'CLX', 'CMA', 'CMCSA', 'CME', 'CMG', 'CMI', 'CMS', 'CMS-PB', 'CNC', 'CNP', 'CNP-PB', 'COF', 'COO', 'COP', 'COST', 'CPB', 'CPRT', 'CPT', 'CRL', 'CRM', 'CRWD', 'CSCO', 'CSGP', 'CSX', 'CTAS', 'CTLT', 'CTRA', 'CTSH', 'CTVA', 'CUK', 'CUKPF', 'CVS', 'CVX', 'CZR', 'D', 'DAL', 'DD', 'DDOG', 'DE', 'DFS', 'DG', 'DGX', 'DHI', 'DHR', 'DIS', 'DISH', 'DLR', 'DLTR', 'DOCU', 'DOV', 'DOW', 'DPUKY', 'DPZ', 'DRI', 'DTE', 'DUK', 'DVA', 'DVN', 'DXC', 'DXCM', 'EA', 'EBAY', 'ECL', 'ED', 'EFX', 'EIX', 'EL', 'ELAA.F', 'ELV', 'EMN', 'EMR', 'ENPH', 'EOG', 'EPAM', 'EQIX', 'EQR', 'EQT', 'ES', 'ESS', 'ETN', 'ETR', 'ETSY', 'EVRG', 'EW', 'EXC', 'EXPD', 'EXPE', 'EXR', 'F', 'FANG', 'FAST', 'FBHS', 'FCX', 'FDS', 'FDX', 'FE', 'FFIV', 'FI', 'FIS', 'FISV', 'FITB', 'FLT', 'FMC', 'FOX', 'FOXA', 'FRC', 'FRCB', 'FRT', 'FTNT', 'FTV', 'FXBY', 'GD', 'GE', 'GEN', 'GILD', 'GIS', 'GLW', 'GM', 'GNRC', 'GOOG', 'GOOGL', 'GPC', 'GPN', 'GRMN', 'GS', 'GS-PK', 'GWW', 'HAL', 'HAS', 'HBAN', 'HBANN', 'HCA', 'HCP', 'HD', 'HES', 'HIG', 'HII', 'HLT', 'HOLX', 'HON', 'HPE', 'HPQ', 'HRL', 'HRS', 'HSIC', 'HST', 'HSY', 'HUM', 'HWM', 'IBM', 'ICE', 'IDXX', 'IEX', 'IFF', 'ILMN', 'INCY', 'INPAP', 'INTC', 'INTU', 'INVH', 'IP', 'IPG', 'IQV', 'IR', 'IRM', 'ISRG', 'IT', 'ITW', 'IVZ', 'J', 'JBHT', 'JCI', 'JD', 'JDCMF', 'JKHY', 'JNJ', 'JNPR', 'JPM', 'K', 'K-WI', 'KDP', 'KEY', 'KEYS', 'KHC', 'KIM', 'KIM-PI', 'KLAC', 'KMB', 'KMI', 'KMX', 'KO', 'KR', 'L', 'LCID', 'LDOS', 'LEN', 'LH', 'LHX', 'LIN', 'LKQ', 'LLY', 'LMT', 'LNC', 'LNT', 'LOW', 'LRCX', 'LULU', 'LUMN', 'LUV', 'LVS', 'LW', 'LYB', 'LYV', 'MA', 'MAA', 'MAR', 'MAS', 'MCD', 'MCHP', 'MCK', 'MCO', 'MDLZ', 'MDT', 'MELI', 'MET', 'META', 'MGM', 'MHK', 'MKC', 'MKTX', 'MLM', 'MMC', 'MMM', 'MNSLV', 'MNST', 'MO', 'MOH', 'MOS', 'MPC', 'MPWR', 'MRK', 'MRNA', 'MRO', 'MRVL', 'MS', 'MSCI', 'MSFT', 'MSI', 'MTB', 'MTCH', 'MTD', 'MU', 'MWRK', 'NCLH', 'NDAQ', 'NDSN', 'NEE', 'NEEXU', 'NEM', 'NETTF', 'NFLX', 'NI', 'NKE', 'NOC', 'NOW', 'NRG', 'NTAP', 'NTES', 'NTRS', 'NUE', 'NVDA', 'NVR', 'NWL', 'NWS', 'NWSA', 'NXPI', 'O', 'OCLCF', 'ODFL', 'OGN', 'OKE', 'OKTA', 'OMC', 'ON', 'ORCL', 'ORLY', 'OTIS', 'OXY', 'PANW', 'PARA', 'PARAA', 'PAYC', 'PAYX', 'PBSTV', 'PCAR', 'PCG', 'PDD', 'PEAK', 'PEG', 'PEP', 'PFE', 'PFG', 'PG', 'PGR', 'PH', 'PHM', 'PKG', 'PKI', 'PLD', 'PLDGP', 'PM', 'PNC', 'PNR', 'PNW', 'POOL', 'PPG', 'PPL', 'PRU', 'PSA', 'PSX', 'PTC', 'PWR', 'PXD', 'PYPL', 'QCOM', 'QRVO', 'RCL', 'RE', 'REG', 'REGN', 'RF', 'RF-PB', 'RHI', 'RJF', 'RL', 'RMD', 'ROK', 'ROL', 'ROP', 'ROST', 'RSG', 'RSMDF', 'RTX', 'SBAC', 'SBNY', 'SBUX', 'SCHW', 'SEDG', 'SEE', 'SGEN', 'SHW', 'SIRI', 'SIVB', 'SJM', 'SLB', 'SNA', 'SNPS', 'SO', 'SPG', 'SPGI', 'SPLK', 'SRE', 'STE', 'STT', 'STX', 'STZ', 'SWK', 'SWKS', 'SYF', 'SYK', 'SYY', 'T', 'TAP', 'TAP-A', 'TDG', 'TDY', 'TEAM', 'TECH', 'TEL', 'TER', 'TFC', 'TFX', 'TGT', 'TJX', 'TMO', 'TMUS', 'TPR', 'TRGP', 'TRMB', 'TROW', 'TRV', 'TSCO', 'TSLA', 'TSN', 'TT', 'TTWO', 'TXN', 'TXT', 'TYL', 'UAL', 'UDR', 'UHID', 'UHS', 'UHT', 'ULTA', 'UNH', 'UNP', 'UPS', 'URI', 'USB', 'V', 'VFC', 'VICI', 'VLO', 'VMC', 'VNO', 'VNORP', 'VRSK', 'VRSN', 'VRTX', 'VTR', 'VTRS', 'VZ', 'WAB', 'WAT', 'WBA', 'WBD', 'WDAY', 'WDC', 'WEC', 'WELL', 'WFC', 'WHR', 'WLTW', 'WM', 'WMB', 'WMT', 'WRB', 'WRK', 'WST', 'WTW', 'WY', 'WYNN', 'XEL', 'XOM', 'XON', 'XRAY', 'XYL', 'YUM', 'ZBH', 'ZBRA', 'ZION', 'ZM', 'ZS', 'ZTS']
565

In [8]:
tickers_to_names_dirty = {t: pts.get_stock_name_by_yahoo_symbol(t) for t in ordered_tickers}

In [9]:
suffixes = [
  r'Holding',
  r'N\.V\.',
  r'Holding N\.V\.',
  r'Properties',
  r'Bancshares',
  r'Companies',
  r'Limited',
  r'Realty',
  r'Inc\.?',
  r'Ltd\.?',
  r'Corporation',
  r'Company',
  r'Group',
  r'& Co\.?',
  r'Co',
  r'PLC',
]

suffixes = sorted(suffixes, key=len, reverse=True)

removal = r'(?:\s|,)*(' + '|'.join(suffixes) + r')(\s|,|$)+'
print(repr(removal))

def clean_name(name):
  # Could not get this fucking regex to work
  if name == 'ASML Holding N.V.':
    return 'ASML'
  prev = None
  while prev != name:
    prev = name
    name = re.sub(removal, '', name, flags=re.IGNORECASE).strip()
  return name

'(?:\\s|,)*(Holding N\\.V\\.|Corporation|Properties|Bancshares|Companies|Holding|Limited|Company|& Co\\.?|N\\.V\\.|Realty|Inc\\.?|Ltd\\.?|Group|PLC|Co)(\\s|,|$)+'

In [10]:
# Redditors don't use yf endings and partial string matches are fine
tickers_to_names = {t: clean_name(n) for t, n in tickers_to_names_dirty.items()}

from collections import defaultdict

# Build reverse mapping
value_to_keys = defaultdict(list)
for k, v in tickers_to_names.items():
  value_to_keys[v].append(k)

associations = {}

successful_associations = 0
failed_associations = 0
successful_resolutions = 0
failed_resolutions = 0
remaining_names = []

goofy_ahh_endings = ('PB','PF','PI', 'PK','PR','A','B','C','F', 'WI', 'MP', 'UKY', 'LV', 'RP', '-PB', 'GP')

for name, tickers in value_to_keys.items():
  n = len(tickers)
  if n == 0:
    raise Exception('how did we get here')
  elif n == 1:
    associations[tickers[0]] = [name, tickers[0]]
    successful_associations += 1
  else:
    primary_tickers = [t for t in tickers if not t.upper().endswith(goofy_ahh_endings)]
    secondary_tickers = [t for t in tickers if t.upper().endswith(goofy_ahh_endings)]
    if len(primary_tickers) == 1 and n - len(secondary_tickers) == 1:
      associations[primary_tickers[0]] = [name, *tickers]
      successful_associations += 1
      successful_resolutions += 1
    elif len(primary_tickers) > 0 and len(secondary_tickers) > 0:
      value_to_keys[name] = primary_tickers
    else:
      failed_resolutions += 1
      failed_associations += 1
      remaining_names.append(name)

print(f'Successful associations: {successful_associations}')
print(f'Failed associations: {failed_associations}')
print(f'Successful resolutions: {successful_resolutions}')
print(f'Failed resolutions: {failed_resolutions}')
print(associations)
for n in remaining_names:
  print(f'{n}: {value_to_keys[n]}')

Successful associations: 502
Failed associations: 16
Successful resolutions: 24
Failed resolutions: 16
{'A': ['Agilent Technologies', 'A'], 'AAL': ['American Airlines', 'AAL'], 'AAP': ['Advance Auto Parts', 'AAP'], 'AAPL': ['Apple', 'AAPL'], 'ABBV': ['AbbVie', 'ABBV'], 'ABC': ['AmerisourceBergen', 'ABC'], 'ABMD': ['Abiomed', 'ABMD'], 'ABNB': ['Airbnb', 'ABNB'], 'ABT': ['Abbott Laboratories', 'ABT'], 'ACGL': ['Arch Capital', 'ACGL'], 'ACN': ['Accenture', 'ACN'], 'ADBE': ['Adobe', 'ADBE'], 'ADI': ['Analog Devices', 'ADI'], 'ADM': ['Archer-Daniels-Midland', 'ADM'], 'ADP': ['Automatic Data Processing', 'ADP'], 'ADSK': ['Autodesk', 'ADSK'], 'ADTN': ['ADTRAN', 'ADTN'], 'AEE': ['Ameren', 'AEE'], 'AEP': ['American Electric Power', 'AEP'], 'AES': ['The AES', 'AES'], 'AFL': ['Aflac', 'AFL'], 'AIG': ['American International', 'AIG'], 'AIZ': ['Assurant', 'AIZ'], 'AJG': ['Arthur J. Gallagher', 'AJG'], 'AKAM': ['Akamai Technologies', 'AKAM'], 'ALB': ['Albemarle', 'ALB'], 'ALGN': ['Align Technology', 'ALGN'], 'ALK': ['Alaska Air', 'ALK'], 'ALL': ['The Allstate', 'ALL'], 'ALLE': ['Allegion', 'ALLE'], 'AMAT': ['Applied Materials', 'AMAT'], 'AMCR': ['Amcor', 'AMCCF', 'AMCR'], 'AMD': ['Advanced Micro Devices', 'AMD'], 'AME': ['AMETEK', 'AME'], 'AMGN': ['Amgen', 'AMGN'], 'AMP': ['Ameriprise Financial', 'AMP'], 'AMT': ['American Tower', 'AMT'], 'AMZN': ['Amazon.com', 'AMZN'], 'ANET': ['Arista Networks', 'ANET'], 'ANSS': ['ANSYS', 'ANSS'], 'AON': ['Aon', 'AON'], 'AOS': ['A. O. Smith', 'AOS'], 'APA': ['Apache', 'APA'], 'APD': ['Air Products and Chemicals', 'APD'], 'APH': ['Amphenol', 'APH'], 'APTV': ['Aptiv', 'APTV'], 'ARE': ['Alexandria Real Estate Equities', 'ARE'], 'ASML': ['ASML', 'ASML', 'ASMLF'], 'ATO': ['Atmos Energy', 'ATO'], 'ATVI': ['Activision Blizzard', 'ATVI'], 'AVB': ['AvalonBay Communities', 'AVB'], 'AVGO': ['Broadcom', 'AVGO'], 'AVY': ['Avery Dennison', 'AVY'], 'AWK': ['American Water Works', 'AWK'], 'AXP': ['American Express', 'AXP'], 'AZN': ['AstraZeneca', 'AZN', 'AZNCF'], 'AZO': ['AutoZone', 'AZO'], 'BA': ['The Boeing', 'BA'], 'BOAPL': ['Bank of America', 'BAC', 'BOAPL'], 'BIDU': ['Baidu', 'BAIDF', 'BIDU'], 'BAX': ['Baxter International', 'BAX'], 'BBWI': ['Bath & Body Works', 'BBWI'], 'BBY': ['Best Buy Co.', 'BBY'], 'BDX': ['Becton, Dickinson and', 'BDX'], 'BEN': ['Franklin Resources', 'BEN'], 'BF-B': ['Brown-Forman', 'BF-B'], 'BIIB': ['Biogen', 'BIIB'], 'BIO': ['Bio-Rad Laboratories', 'BIO'], 'BK': ['The Bank of New York Mellon', 'BK'], 'BKNG': ['Booking Holdings', 'BKNG'], 'BKR': ['Baker Hughes', 'BKR'], 'BLK': ['BlackRock', 'BLK'], 'BMY': ['Bristol-Myers Squibb', 'BMY', 'BMYMP'], 'BR': ['Broadridge Financial Solutions', 'BR'], 'BRK-B': ['Berkshire Hathaway', 'BRK-B'], 'BRO': ['Brown & Brown', 'BRO'], 'BSX': ['Boston Scientific', 'BSX'], 'BWA': ['BorgWarner', 'BWA'], 'BXP': ['Boston', 'BXP'], 'C': ['Citi', 'C'], 'CAG': ['Conagra Brands', 'CAG'], 'CAH': ['Cardinal Health', 'CAH'], 'CARR': ['Carrier Global', 'CARR'], 'CAT': ['Caterpillar', 'CAT'], 'CB': ['Chubb', 'CB'], 'CBRE': ['CBRE', 'CBRE'], 'CCI': ['Crown Castle International Corp', 'CCI'], 'CDAY': ['Ceridian HCM', 'CDAY'], 'CDNS': ['Cadence Design Systems', 'CDNS'], 'CDW': ['CDW', 'CDW'], 'CE': ['Celanese', 'CE'], 'CF': ['CF Industries Holdings', 'CF'], 'CFG': ['Citizens Financial', 'CFG'], 'CHD': ['Church & Dwight Co.', 'CHD'], 'CHRW': ['C.H. Robinson Worldwide', 'CHRW'], 'CHTR': ['Charter Communications', 'CHTR'], 'CI': ['Cigna', 'CI'], 'CINF': ['Cincinnati Financial', 'CINF'], 'CL': ['Colgate-Palmolive', 'CL'], 'CLX': ['The Clorox', 'CLX'], 'CMA': ['Comerica', 'CMA'], 'CMCSA': ['Comcast', 'CMCSA'], 'CME': ['CME', 'CME'], 'CMG': ['Chipotle Mexican Grill', 'CMG'], 'CMI': ['Cummins', 'CMI'], 'CMS': ['CMS Energy', 'CMS', 'CMS-PB'], 'CNC': ['Centene', 'CNC'], 'CNP': ['CenterPoint Energy', 'CNP', 'CNP-PB'], 'COF': ['Capital One Financial', 'COF'], 'COO': ['The Cooper', 'COO'], 'COP': ['ConocoPhillips', 'COP'], 'COST': ['CostWholesale', 'COST'], 'CPB': ['Campbell Soup', 'CPB'], 'CPRT': ['Copart', 'CPRT'], 'CPT': ['Camden Property Trust', 'CPT'], 'CRL': ['Charles River Laboratories International', 'CRL'], 'CRM': ['salesforce.com', 'CRM'], 'CRWD': ['CrowdStrike Holdings', 'CRWD'], 'CSCO': ['CisSystems', 'CSCO'], 'CSGP': ['CoStar', 'CSGP'], 'CSX': ['CSX', 'CSX'], 'CTAS': ['Cintas', 'CTAS'], 'CTLT': ['Catalent', 'CTLT'], 'CTRA': ['Coterra Energy', 'CTRA'], 'CTSH': ['Cognizant Technology Solutions', 'CTSH'], 'CTVA': ['Corteva', 'CTVA'], 'CVS': ['CVS Health', 'CVS'], 'CVX': ['Chevron', 'CVX'], 'CZR': ['Caesars Entertainment', 'CZR'], 'D': ['Dominion Energy', 'D'], 'DAL': ['Delta Air Lines', 'DAL'], 'DD': ['DowDuPont', 'DD'], 'DDOG': ['Datadog', 'DDOG'], 'DE': ['Deere &', 'DE'], 'DFS': ['Discover Financials', 'DFS'], 'DG': ['Dollar General', 'DG'], 'DGX': ['Quest Diagnostics', 'DGX'], 'DHI': ['D.R. Horton', 'DHI'], 'DHR': ['Danaher', 'DHR'], 'DIS': ['The Walt Disney', 'DIS'], 'DISH': ['DISH Network', 'DISH'], 'DLR': ['DigitalTrust', 'DLR'], 'DLTR': ['Dollar Tree', 'DLTR'], 'DOCU': ['DocuSign', 'DOCU'], 'DOV': ['Dover', 'DOV'], 'DOW': ['Dow', 'DOW'], 'DPZ': ["Domino's Pizza", 'DPUKY', 'DPZ'], 'DRI': ['Darden Restaurants', 'DRI'], 'DTE': ['DTE Energy', 'DTE'], 'DUK': ['Duke Energy', 'DUK'], 'DVA': ['DaVita', 'DVA'], 'DVN': ['Devon Energy', 'DVN'], 'DXC': ['DXC Technology', 'DXC'], 'DXCM': ['DexCom', 'DXCM'], 'EA': ['Electronic Arts', 'EA'], 'EBAY': ['eBay', 'EBAY'], 'ECL': ['Ecolab', 'ECL'], 'ED': ['Consolidated Edison', 'ED'], 'EFX': ['Equifax', 'EFX'], 'EIX': ['Edison International', 'EIX'], 'EL': ['The Estée Lauder', 'EL', 'ELAA.F'], 'ELV': ['Elevance Health', 'ELV'], 'EMN': ['Eastman Chemical', 'EMN'], 'EMR': ['Emerson Electric Co.', 'EMR'], 'ENPH': ['Enphase Energy', 'ENPH'], 'EOG': ['EOG Resources', 'EOG'], 'EPAM': ['EPAM Systems', 'EPAM'], 'EQIX': ['Equinix(REIT)', 'EQIX'], 'EQR': ['Equity Residential', 'EQR'], 'EQT': ['EQT', 'EQT'], 'ES': ['Eversource Energy', 'ES'], 'ESS': ['Essex Property Trust', 'ESS'], 'ETN': ['Eaton', 'ETN'], 'ETR': ['Entergy', 'ETR'], 'ETSY': ['Etsy', 'ETSY'], 'EVRG': ['Evergy', 'EVRG'], 'EW': ['Edwards Lifesciences', 'EW'], 'EXC': ['Exelon', 'EXC'], 'EXPD': ['Expeditors International of Washington', 'EXPD'], 'EXPE': ['Expedia', 'EXPE'], 'EXR': ['Extra Space Storage', 'EXR'], 'F': ['Ford Motor', 'F'], 'FANG': ['Diamondback Energy', 'FANG'], 'FAST': ['Fastenal', 'FAST'], 'FBHS': ['Fortune Brands Home & Security', 'FBHS'], 'FCX': ['Freeport-McMoRan', 'FCX'], 'FDS': ['FactSet Research Systems', 'FDS'], 'FDX': ['FedEx', 'FDX'], 'FE': ['FirstEnergy Corp.', 'FE'], 'FFIV': ['F5 Networks', 'FFIV'], 'FIS': ['Fidelity National Information Services', 'FIS'], 'FITB': ['Fifth Third Bancorp', 'FITB'], 'FLT': ['FleetCor Technologies', 'FLT'], 'FMC': ['FMC', 'FMC'], 'FRT': ['FederalInvestment Trust', 'FRT'], 'FTNT': ['Fortinet', 'FTNT'], 'FTV': ['Fortive', 'FTV'], 'GD': ['General Dynamics', 'GD'], 'GE': ['General Electric', 'GE'], 'GEN': ['Gen Digital', 'GEN'], 'GILD': ['Gilead Sciences', 'GILD'], 'GIS': ['General Mills', 'GIS'], 'GLW': ['Corning', 'GLW'], 'GM': ['General Motors', 'GM'], 'GNRC': ['Generac Holdings', 'GNRC'], 'GPC': ['Genuine Parts', 'GPC'], 'GPN': ['Global Payments', 'GPN'], 'GRMN': ['Garmin', 'GRMN'], 'GS': ['The Goldman Sachs', 'GS', 'GS-PK'], 'GWW': ['W.W. Grainger', 'GWW'], 'HAL': ['Halliburton', 'HAL'], 'HAS': ['Hasbro', 'HAS'], 'HCA': ['HCA Healthcare', 'HCA'], 'HD': ['The Home Depot', 'HD'], 'HES': ['Hess', 'HES'], 'HIG': ['The Hartford Financials', 'HIG'], 'HII': ['Huntington Ingalls Industries', 'HII'], 'HLT': ['Hilton Worldwide Holdings', 'HLT'], 'HOLX': ['Hologic', 'HOLX'], 'HON': ['Honeywell International', 'HON'], 'HPE': ['Hewlett Packard Enterprise', 'HPE'], 'HPQ': ['HP', 'HPQ'], 'HRL': ['Hormel Foods', 'HRL'], 'HSIC': ['Henry Schein', 'HSIC'], 'HST': ['Host Hotels & Resorts', 'HST'], 'HSY': ['The Hershey', 'HSY'], 'HUM': ['Humana', 'HUM'], 'HWM': ['Howmet Aerospace', 'HWM'], 'IBM': ['International Business Machines', 'IBM'], 'ICE': ['Intercontinental Exchange', 'ICE'], 'IDXX': ['IDEXX Laboratories', 'IDXX'], 'IEX': ['IDEX', 'IEX'], 'IFF': ['International Flavors & Fragrances', 'IFF'], 'ILMN': ['Illumina', 'ILMN'], 'INCY': ['Incyte', 'INCY'], 'INTC': ['Intel', 'INTC'], 'INTU': ['Intuit', 'INTU'], 'INVH': ['Invitation Homes', 'INVH'], 'IPG': ['The Interpublicof', 'IPG'], 'IQV': ['IQVIA Holdings', 'IQV'], 'IR': ['Ingersoll Rand', 'IR'], 'IRM': ['Iron Mountain', 'IRM'], 'ISRG': ['Intuitive Surgical', 'ISRG'], 'IT': ['Gartner', 'IT'], 'ITW': ['Illinois Tool Works', 'ITW'], 'IVZ': ['Inves', 'IVZ'], 'J': ['Jacobs Engineering', 'J'], 'JBHT': ['J.B. Hunt Transport Services', 'JBHT'], 'JCI': ['Johnson Controls International', 'JCI'], 'JD': ['JD.com', 'JD', 'JDCMF'], 'JKHY': ['Jack Henry & Associates', 'JKHY'], 'JNJ': ['Johnson & Johnson', 'JNJ'], 'JNPR': ['Juniper Networks', 'JNPR'], 'JPM': ['JPMorgan Chase', 'JPM'], 'K': ['Kellogg', 'K', 'K-WI'], 'KDP': ['Keurig Dr Pepper', 'KDP'], 'KEY': ['KeyBank', 'KEY'], 'KEYS': ['Keysight Technologies', 'KEYS'], 'KHC': ['The Kraft Heinz', 'KHC'], 'KIM': ['Kim', 'KIM', 'KIM-PI'], 'KLAC': ['KLA-Tencor', 'KLAC'], 'KMB': ['Kimberly-Clark', 'KMB'], 'KMI': ['Kinder Morgan', 'KMI'], 'KMX': ['CarMax', 'KMX'], 'KO': ['The Coca-Cola', 'KO'], 'KR': ['The Kroger Co.', 'KR'], 'L': ['Loews', 'L'], 'LCID': ['Lucid Motors', 'LCID'], 'LDOS': ['Leidos Holdings', 'LDOS'], 'LEN': ['Lennar', 'LEN'], 'LH': ['Laboratoryof America Holdings', 'LH'], 'LIN': ['Linde', 'LIN'], 'LKQ': ['LKQ', 'LKQ'], 'LLY': ['Eli Lilly and', 'LLY'], 'LMT': ['Lockheed Martin', 'LMT'], 'LNC': ['Lincoln National', 'LNC'], 'LNT': ['Alliant Energy', 'LNT'], 'LOW': ["Lowe's", 'LOW'], 'LRCX': ['Lam Research', 'LRCX'], 'LULU': ['lululemon athletica', 'LULU'], 'LUMN': ['Lumen Technologies', 'LUMN'], 'LUV': ['Southwest Airlines Co.', 'LUV'], 'LVS': ['Las Vegas Sands', 'LVS'], 'LW': ['Lamb Weston Holdings', 'LW'], 'LYB': ['LyondellBasell Industries', 'LYB'], 'LYV': ['Live Nation Entertainment', 'LYV'], 'MA': ['Mastercard', 'MA'], 'MAA': ['Mid-America Apartment Communities', 'MAA'], 'MAR': ['Marriott International', 'MAR'], 'MAS': ['Mas', 'MAS'], 'MCD': ["McDonald's", 'MCD'], 'MCHP': ['Microchip Technology', 'MCHP'], 'MCK': ['McKesson', 'MCK'], 'MCO': ["Moody's", 'MCO'], 'MDLZ': ['Mondelez International', 'MDLZ'], 'MDT': ['Medtronic', 'MDT'], 'MELI': ['Mercado Libre', 'MELI'], 'MET': ['MetLife', 'MET'], 'MWRK': ['Meta Platforms', 'META', 'MWRK'], 'MGM': ['MGM Resorts International', 'MGM'], 'MHK': ['Mohawk Industries', 'MHK'], 'MKC': ['McCormick &', 'MKC'], 'MKTX': ['MarketAxess Holdings', 'MKTX'], 'MLM': ['Martin Marietta Materials', 'MLM'], 'MMC': ['Marsh & McLennan', 'MMC'], 'MMM': ['3M', 'MMM'], 'MS': ['Morgan Stanley', 'MNSLV', 'MS'], 'MNST': ['Monster Beverage', 'MNST'], 'MO': ['Altria', 'MO'], 'MOH': ['Molina Healthcare', 'MOH'], 'MOS': ['The Mosaic', 'MOS'], 'MPC': ['Marathon Petroleum', 'MPC'], 'MPWR': ['Monolithic Power Systems', 'MPWR'], 'MRK': ['Merck', 'MRK'], 'MRNA': ['Moderna', 'MRNA'], 'MRO': ['Marathon Oil', 'MRO'], 'MRVL': ['Marvell Technology', 'MRVL'], 'MSCI': ['MSCI', 'MSCI'], 'MSFT': ['Microsoft', 'MSFT'], 'MSI': ['Motorola Solutions', 'MSI'], 'MTB': ['M&T Bank', 'MTB'], 'MTCH': ['Match', 'MTCH'], 'MTD': ['Mettler-Toledo International', 'MTD'], 'MU': ['Micron Technology', 'MU'], 'NCLH': ['Norwegian Cruise Line Holdings', 'NCLH'], 'NDAQ': ['Nasdaq', 'NDAQ'], 'NDSN': ['Nordson', 'NDSN'], 'NEM': ['Newmont Goldcorp', 'NEM'], 'NTES': ['NetEase', 'NETTF', 'NTES'], 'NFLX': ['Netflix', 'NFLX'], 'NI': ['NiSource', 'NI'], 'NKE': ['Nike', 'NKE'], 'NOC': ['Northrop Grumman', 'NOC'], 'NOW': ['ServiceNow', 'NOW'], 'NRG': ['NRG Energy', 'NRG'], 'NTAP': ['NetApp', 'NTAP'], 'NTRS': ['Northern Trust', 'NTRS'], 'NUE': ['Nucor', 'NUE'], 'NVDA': ['NVIDIA', 'NVDA'], 'NVR': ['NVR', 'NVR'], 'NWL': ['Newell Brands', 'NWL'], 'NWS': ['News', 'NWS', 'NWSA'], 'NXPI': ['NXP Semiconductors', 'NXPI'], 'ORCL': ['Oracle', 'OCLCF', 'ORCL'], 'ODFL': ['Old Dominion Freight Line', 'ODFL'], 'OGN': ['Organon', 'OGN'], 'OKE': ['ONEOK', 'OKE'], 'OKTA': ['Okta', 'OKTA'], 'OMC': ['Omnicom', 'OMC'], 'ON': ['ON Semiconductor', 'ON'], 'ORLY': ["O'Reilly Automotive", 'ORLY'], 'OTIS': ['Otis Worldwide', 'OTIS'], 'OXY': ['Occidental Petroleum', 'OXY'], 'PANW': ['Palo Alto Networks', 'PANW'], 'PAYC': ['Paycom Software', 'PAYC'], 'PAYX': ['Paychex', 'PAYX'], 'PBSTV': ['Public Storage', 'PBSTV', 'PSA'], 'PCAR': ['PACCAR', 'PCAR'], 'PCG': ['PG&E', 'PCG'], 'PDD': ['Pinduoduo', 'PDD'], 'PEG': ['Public Service Enterprise', 'PEG'], 'PEP': ['Pepsi', 'PEP'], 'PFE': ['Pfizer', 'PFE'], 'PFG': ['Principal Financial', 'PFG'], 'PG': ['The Procter & Gamble', 'PG'], 'PGR': ['The Progressive', 'PGR'], 'PH': ['Parker-Hannifin', 'PH'], 'PHM': ['Pulte', 'PHM'], 'PKG': ['Packagingof America', 'PKG'], 'PKI': ['PerkinElmer', 'PKI'], 'PLD': ['Prologis', 'PLD', 'PLDGP'], 'PM': ['Philip Morris International', 'PM'], 'PNC': ['The PNC Financials', 'PNC'], 'PNR': ['Pentair', 'PNR'], 'PNW': ['Pinnacle West Capital', 'PNW'], 'POOL': ['Pool', 'POOL'], 'PPG': ['PPG Industries', 'PPG'], 'PPL': ['PPL', 'PPL'], 'PRU': ['Prudential Financial', 'PRU'], 'PSX': ['Phillips 66', 'PSX'], 'PTC': ['PTC', 'PTC'], 'PWR': ['Quanta Services', 'PWR'], 'PXD': ['Pioneer Natural Resources', 'PXD'], 'PYPL': ['PayPal Holdings', 'PYPL'], 'QCOM': ['Qualcomm', 'QCOM'], 'QRVO': ['Qorvo', 'QRVO'], 'RCL': ['Royal Caribbean Cruises', 'RCL'], 'RE': ['Everest Re', 'RE'], 'REG': ['Regency Centers', 'REG'], 'REGN': ['Regeneron Pharmaceuticals', 'REGN'], 'RHI': ['Robert Half International', 'RHI'], 'RJF': ['Raymond James Financial', 'RJF'], 'RL': ['Ralph Lauren', 'RL'], 'RMD': ['ResMed', 'RMD', 'RSMDF'], 'ROK': ['Rockwell Automation', 'ROK'], 'ROL': ['Rollins', 'ROL'], 'ROP': ['Roper Technologies', 'ROP'], 'ROST': ['Ross Stores', 'ROST'], 'RSG': ['Republic Services', 'RSG'], 'RTX': ['Raytheon', 'RTX'], 'SBAC': ['SBA Communications', 'SBAC'], 'SBNY': ['Signature Bank', 'SBNY'], 'SBUX': ['Starbucks', 'SBUX'], 'SCHW': ['The Charles Schwab', 'SCHW'], 'SEDG': ['SolarEdge Technologies', 'SEDG'], 'SEE': ['Sealed Air', 'SEE'], 'SGEN': ['Seagen', 'SGEN'], 'SHW': ['The Sherwin-Williams', 'SHW'], 'SIRI': ['Sirius XM Holdings', 'SIRI'], 'SIVB': ['SVB Financial', 'SIVB'], 'SJM': ['The J. M. Smucker', 'SJM'], 'SLB': ['Schlumberger', 'SLB'], 'SNA': ['Snap-on', 'SNA'], 'SNPS': ['Synopsys', 'SNPS'], 'SO': ['Southern', 'SO'], 'SPG': ['Simon Property', 'SPG'], 'SPGI': ['S&P Global', 'SPGI'], 'SPLK': ['Splunk', 'SPLK'], 'SRE': ['Sempra Energy', 'SRE'], 'STE': ['STERIS', 'STE'], 'STT': ['State Street', 'STT'], 'STX': ['Seagate Technology', 'STX'], 'SWK': ['Stanley Black & Decker', 'SWK'], 'SWKS': ['Skyworks Solutions', 'SWKS'], 'SYF': ['Synchrony Financial', 'SYF'], 'SYK': ['Stryker', 'SYK'], 'SYY': ['Sys', 'SYY'], 'T': ['AT&T', 'T'], 'TAP': ['Molson Coors Beverage', 'TAP', 'TAP-A'], 'TDG': ['TransDigm', 'TDG'], 'TDY': ['Teledyne Technologies Incorporated', 'TDY'], 'TEAM': ['Atlassian', 'TEAM'], 'TECH': ['Bio-Techne', 'TECH'], 'TEL': ['TE Connectivity', 'TEL'], 'TER': ['Teradyne', 'TER'], 'TFC': ['Truist Financial', 'TFC'], 'TFX': ['Teleflex', 'TFX'], 'TGT': ['Target', 'TGT'], 'TJX': ['The TJX', 'TJX'], 'TMO': ['Thermo Fisher Scientific', 'TMO'], 'TMUS': ['T-Mobile US', 'TMUS'], 'TPR': ['Tapestry', 'TPR'], 'TRGP': ['Targa Resources Corp.', 'TRGP'], 'TRMB': ['Trimble', 'TRMB'], 'TROW': ['T. Rowe Price', 'TROW'], 'TRV': ['The Travelers', 'TRV'], 'TSCO': ['Tractor Supply', 'TSCO'], 'TSLA': ['Tesla', 'TSLA'], 'TSN': ['Tyson Foods', 'TSN'], 'TT': ['Trane Technologies', 'TT'], 'TTWO': ['Take-Two Interactive Software', 'TTWO'], 'TXN': ['Texas Instruments', 'TXN'], 'TXT': ['Textron', 'TXT'], 'TYL': ['Tyler Technologies', 'TYL'], 'UAL': ['United Continental Holdings', 'UAL'], 'UDR': ['UDR', 'UDR'], 'ULTA': ['Ulta Beauty', 'ULTA'], 'UNH': ['UnitedHealth', 'UNH'], 'UNP': ['Union Pacific', 'UNP'], 'UPS': ['United Parcel Service', 'UPS'], 'URI': ['United Rentals', 'URI'], 'USB': ['U.S. Bancorp', 'USB'], 'V': ['Visa', 'V'], 'VFC': ['V.F.', 'VFC'], 'VICI': ['Vici', 'VICI'], 'VLO': ['Valero Energy', 'VLO'], 'VMC': ['Vulcan Materials', 'VMC'], 'VNO': ['VornadoTrust', 'VNO', 'VNORP'], 'VRSK': ['Verisk Analytics', 'VRSK'], 'VRSN': ['VeriSign', 'VRSN'], 'VRTX': ['Vertex Pharmaceuticals', 'VRTX'], 'VTR': ['Ventas', 'VTR'], 'VTRS': ['Viatris', 'VTRS'], 'VZ': ['Verizon Communications', 'VZ'], 'WAB': ['Wabtec', 'WAB'], 'WAT': ['Waters', 'WAT'], 'WBA': ['Walgreens Boots Alliance', 'WBA'], 'WBD': ['Warner Bros. Discovery', 'WBD'], 'WDAY': ['Workday', 'WDAY'], 'WDC': ['Western Digital', 'WDC'], 'WEC': ['WEC Energy', 'WEC'], 'WELL': ['Welltower', 'WELL'], 'WFC': ['Wells Fargo &', 'WFC'], 'WHR': ['Whirlpool', 'WHR'], 'WM': ['Waste Management', 'WM'], 'WMB': ['The Williams', 'WMB'], 'WMT': ['Walmart', 'WMT'], 'WRB': ['W. R. Berkley', 'WRB'], 'WRK': ['WestRock', 'WRK'], 'WST': ['West Pharmaceutical Services', 'WST'], 'WY': ['Weyerhaeuser', 'WY'], 'WYNN': ['Wynn Resorts', 'WYNN'], 'XEL': ['Xcel Energy', 'XEL'], 'XRAY': ['Dentyply Sirona', 'XRAY'], 'XYL': ['Xylem', 'XYL'], 'YUM': ['YUM! Brands', 'YUM'], 'ZBH': ['Zimmer Biomet Holdings', 'ZBH'], 'ZBRA': ['Zebra Technologies', 'ZBRA'], 'ZION': ['Zions BanNational Association', 'ZION'], 'ZM': ['Zoom Video Communications', 'ZM'], 'ZS': ['Zscaler', 'ZS'], 'ZTS': ['Zoetis', 'ZTS']}
Ball: ['BALL', 'BALY', 'BLL']
Constellation Brands: ['CEG', 'STZ']
Fiserv: ['FI', 'FISV']
First Republic Bank: ['FRC', 'FRCB']
Alphabet: ['GOOG', 'GOOGL']
Huntington: ['HBAN', 'HBANN']
Healthpeak: ['HCP', 'PEAK']
L3Harris Technologies: ['HRS', 'LHX']
International Paper: ['INPAP', 'IP']
NextEra Energy: ['NEE', 'NEEXU']
Income: ['O', 'UHT']
Paramount Global: ['PARA', 'PARAA']
Regions Financial: ['RF', 'RF-PB']
Universal Health Services: ['UHID', 'UHS']
WTW Public: ['WLTW', 'WTW']
Exxon Mobil: ['XOM', 'XON']

In [ ]:
# Just hardcoding the rest

associations['FISV'] = ['Fiserv', 'FI', 'FISV']
associations['FRCB'] = ['First Republic Bank', 'FRCB', 'FRC']
associations['GOOG'] = ['Alphabet', 'GOOG', 'GOOGL']
associations['HBAN'] = ['Huntington', 'Huntington Bancshares', 'HBAN', 'HBANN']
associations['LHX'] = ['L3Harris', 'HRS', 'LHX']
associations['IP'] = ['International Paper', 'INPAP', 'IP']
associations['NEE'] = ['NextEra Energy', 'NEE', 'NEEXU']
associations['O'] = ['Realty Income', 'Realty Income Corp', 'O',]
associations['UHT'] = ['Universal Health Realty', 'UHT']
associations['PSKY'] = ['Paramount', 'Paramount Skydance', 'PARA', 'PARAA', 'PSKY']
associations['RF'] = ['Regions Financial', 'RF', 'RF-PB']
associations['UHS'] = ['Universal Health Services', 'UHID', 'UHS']
associations['WTW'] = ['WTW Public', 'Willis Towers Watson', 'WTW', 'WLTW']
associations['XOM'] = ['Exxon Mobil', 'XOM', 'XON']

# Confused for real english words or common abbreviations
del associations['A']
del associations['COO']
del associations['BRO']
del associations['L']

# Ignoring BALL and CEG/STZ because source data is wrong
# Ignoring Healthpeak because there are a lot of conflicts with these tickers and it'll convolute the data

# Manually adding meme stocks

associations['GME'] = ['GME', 'GameStop']
associations['AMC'] = ['AMC']
associations['BB'] = ['BB', 'BlackBerry']
associations['KOSS'] = ['KOSS', 'Koss']
associations['NOK'] = ['NOK', 'Nokia']
associations['EXPR'] = ['EXPR', 'Express']
associations['SNDL'] = ['SNDL', 'SunDial']
associations['BBBY'] = ['BBBY', 'Bed Bath Beyond', 'Bed Bath & Beyond']
associations['PLTR'] = ['PLTR', 'Palantir']
associations['CLOV'] = ['CLOV', 'Clover']
associations['SPCE'] = ['SPCE', 'Virgin Galactic']
associations['VIR'] = ['VIR']
associations['FUBO'] = ['FUBO', 'Fubo', 'Fubotv']
associations['BYND'] = ['BYND', 'Beyond']
associations['WISH'] = ['WISH', 'ContextLogic']
associations['CVNA'] = ['CVNA', 'Carvana']
associations['UPST'] = ['UPST', 'Upstart']
associations['NDAQ'] += ['QQQ', 'QQQM']
associations['QQQ'] = associations['NDAQ']
del associations['NDAQ']
associations['SPY'] = ['SPY', 'SPX', 'SP500', 'S&P500']
print(associations)

{'AAL': ['American Airlines', 'AAL'], 'AAP': ['Advance Auto Parts', 'AAP'], 'AAPL': ['Apple', 'AAPL'], 'ABBV': ['AbbVie', 'ABBV'], 'ABC': ['AmerisourceBergen', 'ABC'], 'ABMD': ['Abiomed', 'ABMD'], 'ABNB': ['Airbnb', 'ABNB'], 'ABT': ['Abbott Laboratories', 'ABT'], 'ACGL': ['Arch Capital', 'ACGL'], 'ACN': ['Accenture', 'ACN'], 'ADBE': ['Adobe', 'ADBE'], 'ADI': ['Analog Devices', 'ADI'], 'ADM': ['Archer-Daniels-Midland', 'ADM'], 'ADP': ['Automatic Data Processing', 'ADP'], 'ADSK': ['Autodesk', 'ADSK'], 'ADTN': ['ADTRAN', 'ADTN'], 'AEE': ['Ameren', 'AEE'], 'AEP': ['American Electric Power', 'AEP'], 'AES': ['The AES', 'AES'], 'AFL': ['Aflac', 'AFL'], 'AIG': ['American International', 'AIG'], 'AIZ': ['Assurant', 'AIZ'], 'AJG': ['Arthur J. Gallagher', 'AJG'], 'AKAM': ['Akamai Technologies', 'AKAM'], 'ALB': ['Albemarle', 'ALB'], 'ALGN': ['Align Technology', 'ALGN'], 'ALK': ['Alaska Air', 'ALK'], 'ALL': ['The Allstate', 'ALL'], 'ALLE': ['Allegion', 'ALLE'], 'AMAT': ['Applied Materials', 'AMAT'], 'AMCR': ['Amcor', 'AMCCF', 'AMCR'], 'AMD': ['Advanced Micro Devices', 'AMD'], 'AME': ['AMETEK', 'AME'], 'AMGN': ['Amgen', 'AMGN'], 'AMP': ['Ameriprise Financial', 'AMP'], 'AMT': ['American Tower', 'AMT'], 'AMZN': ['Amazon.com', 'AMZN'], 'ANET': ['Arista Networks', 'ANET'], 'ANSS': ['ANSYS', 'ANSS'], 'AON': ['Aon', 'AON'], 'AOS': ['A. O. Smith', 'AOS'], 'APA': ['Apache', 'APA'], 'APD': ['Air Products and Chemicals', 'APD'], 'APH': ['Amphenol', 'APH'], 'APTV': ['Aptiv', 'APTV'], 'ARE': ['Alexandria Real Estate Equities', 'ARE'], 'ASML': ['ASML', 'ASML', 'ASMLF'], 'ATO': ['Atmos Energy', 'ATO'], 'ATVI': ['Activision Blizzard', 'ATVI'], 'AVB': ['AvalonBay Communities', 'AVB'], 'AVGO': ['Broadcom', 'AVGO'], 'AVY': ['Avery Dennison', 'AVY'], 'AWK': ['American Water Works', 'AWK'], 'AXP': ['American Express', 'AXP'], 'AZN': ['AstraZeneca', 'AZN', 'AZNCF'], 'AZO': ['AutoZone', 'AZO'], 'BA': ['The Boeing', 'BA'], 'BOAPL': ['Bank of America', 'BAC', 'BOAPL'], 'BIDU': ['Baidu', 'BAIDF', 'BIDU'], 'BAX': ['Baxter International', 'BAX'], 'BBWI': ['Bath & Body Works', 'BBWI'], 'BBY': ['Best Buy Co.', 'BBY'], 'BDX': ['Becton, Dickinson and', 'BDX'], 'BEN': ['Franklin Resources', 'BEN'], 'BF-B': ['Brown-Forman', 'BF-B'], 'BIIB': ['Biogen', 'BIIB'], 'BIO': ['Bio-Rad Laboratories', 'BIO'], 'BK': ['The Bank of New York Mellon', 'BK'], 'BKNG': ['Booking Holdings', 'BKNG'], 'BKR': ['Baker Hughes', 'BKR'], 'BLK': ['BlackRock', 'BLK'], 'BMY': ['Bristol-Myers Squibb', 'BMY', 'BMYMP'], 'BR': ['Broadridge Financial Solutions', 'BR'], 'BRK-B': ['Berkshire Hathaway', 'BRK-B'], 'BRO': ['Brown & Brown', 'BRO'], 'BSX': ['Boston Scientific', 'BSX'], 'BWA': ['BorgWarner', 'BWA'], 'BXP': ['Boston', 'BXP'], 'C': ['Citi', 'C'], 'CAG': ['Conagra Brands', 'CAG'], 'CAH': ['Cardinal Health', 'CAH'], 'CARR': ['Carrier Global', 'CARR'], 'CAT': ['Caterpillar', 'CAT'], 'CB': ['Chubb', 'CB'], 'CBRE': ['CBRE', 'CBRE'], 'CCI': ['Crown Castle International Corp', 'CCI'], 'CDAY': ['Ceridian HCM', 'CDAY'], 'CDNS': ['Cadence Design Systems', 'CDNS'], 'CDW': ['CDW', 'CDW'], 'CE': ['Celanese', 'CE'], 'CF': ['CF Industries Holdings', 'CF'], 'CFG': ['Citizens Financial', 'CFG'], 'CHD': ['Church & Dwight Co.', 'CHD'], 'CHRW': ['C.H. Robinson Worldwide', 'CHRW'], 'CHTR': ['Charter Communications', 'CHTR'], 'CI': ['Cigna', 'CI'], 'CINF': ['Cincinnati Financial', 'CINF'], 'CL': ['Colgate-Palmolive', 'CL'], 'CLX': ['The Clorox', 'CLX'], 'CMA': ['Comerica', 'CMA'], 'CMCSA': ['Comcast', 'CMCSA'], 'CME': ['CME', 'CME'], 'CMG': ['Chipotle Mexican Grill', 'CMG'], 'CMI': ['Cummins', 'CMI'], 'CMS': ['CMS Energy', 'CMS', 'CMS-PB'], 'CNC': ['Centene', 'CNC'], 'CNP': ['CenterPoint Energy', 'CNP', 'CNP-PB'], 'COF': ['Capital One Financial', 'COF'], 'COO': ['The Cooper', 'COO'], 'COP': ['ConocoPhillips', 'COP'], 'COST': ['CostWholesale', 'COST'], 'CPB': ['Campbell Soup', 'CPB'], 'CPRT': ['Copart', 'CPRT'], 'CPT': ['Camden Property Trust', 'CPT'], 'CRL': ['Charles River Laboratories International', 'CRL'], 'CRM': ['salesforce.com', 'CRM'], 'CRWD': ['CrowdStrike Holdings', 'CRWD'], 'CSCO': ['CisSystems', 'CSCO'], 'CSGP': ['CoStar', 'CSGP'], 'CSX': ['CSX', 'CSX'], 'CTAS': ['Cintas', 'CTAS'], 'CTLT': ['Catalent', 'CTLT'], 'CTRA': ['Coterra Energy', 'CTRA'], 'CTSH': ['Cognizant Technology Solutions', 'CTSH'], 'CTVA': ['Corteva', 'CTVA'], 'CVS': ['CVS Health', 'CVS'], 'CVX': ['Chevron', 'CVX'], 'CZR': ['Caesars Entertainment', 'CZR'], 'D': ['Dominion Energy', 'D'], 'DAL': ['Delta Air Lines', 'DAL'], 'DD': ['DowDuPont', 'DD'], 'DDOG': ['Datadog', 'DDOG'], 'DE': ['Deere &', 'DE'], 'DFS': ['Discover Financials', 'DFS'], 'DG': ['Dollar General', 'DG'], 'DGX': ['Quest Diagnostics', 'DGX'], 'DHI': ['D.R. Horton', 'DHI'], 'DHR': ['Danaher', 'DHR'], 'DIS': ['The Walt Disney', 'DIS'], 'DISH': ['DISH Network', 'DISH'], 'DLR': ['DigitalTrust', 'DLR'], 'DLTR': ['Dollar Tree', 'DLTR'], 'DOCU': ['DocuSign', 'DOCU'], 'DOV': ['Dover', 'DOV'], 'DOW': ['Dow', 'DOW'], 'DPZ': ["Domino's Pizza", 'DPUKY', 'DPZ'], 'DRI': ['Darden Restaurants', 'DRI'], 'DTE': ['DTE Energy', 'DTE'], 'DUK': ['Duke Energy', 'DUK'], 'DVA': ['DaVita', 'DVA'], 'DVN': ['Devon Energy', 'DVN'], 'DXC': ['DXC Technology', 'DXC'], 'DXCM': ['DexCom', 'DXCM'], 'EA': ['Electronic Arts', 'EA'], 'EBAY': ['eBay', 'EBAY'], 'ECL': ['Ecolab', 'ECL'], 'ED': ['Consolidated Edison', 'ED'], 'EFX': ['Equifax', 'EFX'], 'EIX': ['Edison International', 'EIX'], 'EL': ['The Estée Lauder', 'EL', 'ELAA.F'], 'ELV': ['Elevance Health', 'ELV'], 'EMN': ['Eastman Chemical', 'EMN'], 'EMR': ['Emerson Electric Co.', 'EMR'], 'ENPH': ['Enphase Energy', 'ENPH'], 'EOG': ['EOG Resources', 'EOG'], 'EPAM': ['EPAM Systems', 'EPAM'], 'EQIX': ['Equinix(REIT)', 'EQIX'], 'EQR': ['Equity Residential', 'EQR'], 'EQT': ['EQT', 'EQT'], 'ES': ['Eversource Energy', 'ES'], 'ESS': ['Essex Property Trust', 'ESS'], 'ETN': ['Eaton', 'ETN'], 'ETR': ['Entergy', 'ETR'], 'ETSY': ['Etsy', 'ETSY'], 'EVRG': ['Evergy', 'EVRG'], 'EW': ['Edwards Lifesciences', 'EW'], 'EXC': ['Exelon', 'EXC'], 'EXPD': ['Expeditors International of Washington', 'EXPD'], 'EXPE': ['Expedia', 'EXPE'], 'EXR': ['Extra Space Storage', 'EXR'], 'F': ['Ford Motor', 'F'], 'FANG': ['Diamondback Energy', 'FANG'], 'FAST': ['Fastenal', 'FAST'], 'FBHS': ['Fortune Brands Home & Security', 'FBHS'], 'FCX': ['Freeport-McMoRan', 'FCX'], 'FDS': ['FactSet Research Systems', 'FDS'], 'FDX': ['FedEx', 'FDX'], 'FE': ['FirstEnergy Corp.', 'FE'], 'FFIV': ['F5 Networks', 'FFIV'], 'FIS': ['Fidelity National Information Services', 'FIS'], 'FITB': ['Fifth Third Bancorp', 'FITB'], 'FLT': ['FleetCor Technologies', 'FLT'], 'FMC': ['FMC', 'FMC'], 'FRT': ['FederalInvestment Trust', 'FRT'], 'FTNT': ['Fortinet', 'FTNT'], 'FTV': ['Fortive', 'FTV'], 'GD': ['General Dynamics', 'GD'], 'GE': ['General Electric', 'GE'], 'GEN': ['Gen Digital', 'GEN'], 'GILD': ['Gilead Sciences', 'GILD'], 'GIS': ['General Mills', 'GIS'], 'GLW': ['Corning', 'GLW'], 'GM': ['General Motors', 'GM'], 'GNRC': ['Generac Holdings', 'GNRC'], 'GPC': ['Genuine Parts', 'GPC'], 'GPN': ['Global Payments', 'GPN'], 'GRMN': ['Garmin', 'GRMN'], 'GS': ['The Goldman Sachs', 'GS', 'GS-PK'], 'GWW': ['W.W. Grainger', 'GWW'], 'HAL': ['Halliburton', 'HAL'], 'HAS': ['Hasbro', 'HAS'], 'HCA': ['HCA Healthcare', 'HCA'], 'HD': ['The Home Depot', 'HD'], 'HES': ['Hess', 'HES'], 'HIG': ['The Hartford Financials', 'HIG'], 'HII': ['Huntington Ingalls Industries', 'HII'], 'HLT': ['Hilton Worldwide Holdings', 'HLT'], 'HOLX': ['Hologic', 'HOLX'], 'HON': ['Honeywell International', 'HON'], 'HPE': ['Hewlett Packard Enterprise', 'HPE'], 'HPQ': ['HP', 'HPQ'], 'HRL': ['Hormel Foods', 'HRL'], 'HSIC': ['Henry Schein', 'HSIC'], 'HST': ['Host Hotels & Resorts', 'HST'], 'HSY': ['The Hershey', 'HSY'], 'HUM': ['Humana', 'HUM'], 'HWM': ['Howmet Aerospace', 'HWM'], 'IBM': ['International Business Machines', 'IBM'], 'ICE': ['Intercontinental Exchange', 'ICE'], 'IDXX': ['IDEXX Laboratories', 'IDXX'], 'IEX': ['IDEX', 'IEX'], 'IFF': ['International Flavors & Fragrances', 'IFF'], 'ILMN': ['Illumina', 'ILMN'], 'INCY': ['Incyte', 'INCY'], 'INTC': ['Intel', 'INTC'], 'INTU': ['Intuit', 'INTU'], 'INVH': ['Invitation Homes', 'INVH'], 'IPG': ['The Interpublicof', 'IPG'], 'IQV': ['IQVIA Holdings', 'IQV'], 'IR': ['Ingersoll Rand', 'IR'], 'IRM': ['Iron Mountain', 'IRM'], 'ISRG': ['Intuitive Surgical', 'ISRG'], 'IT': ['Gartner', 'IT'], 'ITW': ['Illinois Tool Works', 'ITW'], 'IVZ': ['Inves', 'IVZ'], 'J': ['Jacobs Engineering', 'J'], 'JBHT': ['J.B. Hunt Transport Services', 'JBHT'], 'JCI': ['Johnson Controls International', 'JCI'], 'JD': ['JD.com', 'JD', 'JDCMF'], 'JKHY': ['Jack Henry & Associates', 'JKHY'], 'JNJ': ['Johnson & Johnson', 'JNJ'], 'JNPR': ['Juniper Networks', 'JNPR'], 'JPM': ['JPMorgan Chase', 'JPM'], 'K': ['Kellogg', 'K', 'K-WI'], 'KDP': ['Keurig Dr Pepper', 'KDP'], 'KEY': ['KeyBank', 'KEY'], 'KEYS': ['Keysight Technologies', 'KEYS'], 'KHC': ['The Kraft Heinz', 'KHC'], 'KIM': ['Kim', 'KIM', 'KIM-PI'], 'KLAC': ['KLA-Tencor', 'KLAC'], 'KMB': ['Kimberly-Clark', 'KMB'], 'KMI': ['Kinder Morgan', 'KMI'], 'KMX': ['CarMax', 'KMX'], 'KO': ['The Coca-Cola', 'KO'], 'KR': ['The Kroger Co.', 'KR'], 'L': ['Loews', 'L'], 'LCID': ['Lucid Motors', 'LCID'], 'LDOS': ['Leidos Holdings', 'LDOS'], 'LEN': ['Lennar', 'LEN'], 'LH': ['Laboratoryof America Holdings', 'LH'], 'LIN': ['Linde', 'LIN'], 'LKQ': ['LKQ', 'LKQ'], 'LLY': ['Eli Lilly and', 'LLY'], 'LMT': ['Lockheed Martin', 'LMT'], 'LNC': ['Lincoln National', 'LNC'], 'LNT': ['Alliant Energy', 'LNT'], 'LOW': ["Lowe's", 'LOW'], 'LRCX': ['Lam Research', 'LRCX'], 'LULU': ['lululemon athletica', 'LULU'], 'LUMN': ['Lumen Technologies', 'LUMN'], 'LUV': ['Southwest Airlines Co.', 'LUV'], 'LVS': ['Las Vegas Sands', 'LVS'], 'LW': ['Lamb Weston Holdings', 'LW'], 'LYB': ['LyondellBasell Industries', 'LYB'], 'LYV': ['Live Nation Entertainment', 'LYV'], 'MA': ['Mastercard', 'MA'], 'MAA': ['Mid-America Apartment Communities', 'MAA'], 'MAR': ['Marriott International', 'MAR'], 'MAS': ['Mas', 'MAS'], 'MCD': ["McDonald's", 'MCD'], 'MCHP': ['Microchip Technology', 'MCHP'], 'MCK': ['McKesson', 'MCK'], 'MCO': ["Moody's", 'MCO'], 'MDLZ': ['Mondelez International', 'MDLZ'], 'MDT': ['Medtronic', 'MDT'], 'MELI': ['Mercado Libre', 'MELI'], 'MET': ['MetLife', 'MET'], 'MWRK': ['Meta Platforms', 'META', 'MWRK'], 'MGM': ['MGM Resorts International', 'MGM'], 'MHK': ['Mohawk Industries', 'MHK'], 'MKC': ['McCormick &', 'MKC'], 'MKTX': ['MarketAxess Holdings', 'MKTX'], 'MLM': ['Martin Marietta Materials', 'MLM'], 'MMC': ['Marsh & McLennan', 'MMC'], 'MMM': ['3M', 'MMM'], 'MS': ['Morgan Stanley', 'MNSLV', 'MS'], 'MNST': ['Monster Beverage', 'MNST'], 'MO': ['Altria', 'MO'], 'MOH': ['Molina Healthcare', 'MOH'], 'MOS': ['The Mosaic', 'MOS'], 'MPC': ['Marathon Petroleum', 'MPC'], 'MPWR': ['Monolithic Power Systems', 'MPWR'], 'MRK': ['Merck', 'MRK'], 'MRNA': ['Moderna', 'MRNA'], 'MRO': ['Marathon Oil', 'MRO'], 'MRVL': ['Marvell Technology', 'MRVL'], 'MSCI': ['MSCI', 'MSCI'], 'MSFT': ['Microsoft', 'MSFT'], 'MSI': ['Motorola Solutions', 'MSI'], 'MTB': ['M&T Bank', 'MTB'], 'MTCH': ['Match', 'MTCH'], 'MTD': ['Mettler-Toledo International', 'MTD'], 'MU': ['Micron Technology', 'MU'], 'NCLH': ['Norwegian Cruise Line Holdings', 'NCLH'], 'NDSN': ['Nordson', 'NDSN'], 'NEM': ['Newmont Goldcorp', 'NEM'], 'NTES': ['NetEase', 'NETTF', 'NTES'], 'NFLX': ['Netflix', 'NFLX'], 'NI': ['NiSource', 'NI'], 'NKE': ['Nike', 'NKE'], 'NOC': ['Northrop Grumman', 'NOC'], 'NOW': ['ServiceNow', 'NOW'], 'NRG': ['NRG Energy', 'NRG'], 'NTAP': ['NetApp', 'NTAP'], 'NTRS': ['Northern Trust', 'NTRS'], 'NUE': ['Nucor', 'NUE'], 'NVDA': ['NVIDIA', 'NVDA'], 'NVR': ['NVR', 'NVR'], 'NWL': ['Newell Brands', 'NWL'], 'NWS': ['News', 'NWS', 'NWSA'], 'NXPI': ['NXP Semiconductors', 'NXPI'], 'ORCL': ['Oracle', 'OCLCF', 'ORCL'], 'ODFL': ['Old Dominion Freight Line', 'ODFL'], 'OGN': ['Organon', 'OGN'], 'OKE': ['ONEOK', 'OKE'], 'OKTA': ['Okta', 'OKTA'], 'OMC': ['Omnicom', 'OMC'], 'ON': ['ON Semiconductor', 'ON'], 'ORLY': ["O'Reilly Automotive", 'ORLY'], 'OTIS': ['Otis Worldwide', 'OTIS'], 'OXY': ['Occidental Petroleum', 'OXY'], 'PANW': ['Palo Alto Networks', 'PANW'], 'PAYC': ['Paycom Software', 'PAYC'], 'PAYX': ['Paychex', 'PAYX'], 'PBSTV': ['Public Storage', 'PBSTV', 'PSA'], 'PCAR': ['PACCAR', 'PCAR'], 'PCG': ['PG&E', 'PCG'], 'PDD': ['Pinduoduo', 'PDD'], 'PEG': ['Public Service Enterprise', 'PEG'], 'PEP': ['Pepsi', 'PEP'], 'PFE': ['Pfizer', 'PFE'], 'PFG': ['Principal Financial', 'PFG'], 'PG': ['The Procter & Gamble', 'PG'], 'PGR': ['The Progressive', 'PGR'], 'PH': ['Parker-Hannifin', 'PH'], 'PHM': ['Pulte', 'PHM'], 'PKG': ['Packagingof America', 'PKG'], 'PKI': ['PerkinElmer', 'PKI'], 'PLD': ['Prologis', 'PLD', 'PLDGP'], 'PM': ['Philip Morris International', 'PM'], 'PNC': ['The PNC Financials', 'PNC'], 'PNR': ['Pentair', 'PNR'], 'PNW': ['Pinnacle West Capital', 'PNW'], 'POOL': ['Pool', 'POOL'], 'PPG': ['PPG Industries', 'PPG'], 'PPL': ['PPL', 'PPL'], 'PRU': ['Prudential Financial', 'PRU'], 'PSX': ['Phillips 66', 'PSX'], 'PTC': ['PTC', 'PTC'], 'PWR': ['Quanta Services', 'PWR'], 'PXD': ['Pioneer Natural Resources', 'PXD'], 'PYPL': ['PayPal Holdings', 'PYPL'], 'QCOM': ['Qualcomm', 'QCOM'], 'QRVO': ['Qorvo', 'QRVO'], 'RCL': ['Royal Caribbean Cruises', 'RCL'], 'RE': ['Everest Re', 'RE'], 'REG': ['Regency Centers', 'REG'], 'REGN': ['Regeneron Pharmaceuticals', 'REGN'], 'RHI': ['Robert Half International', 'RHI'], 'RJF': ['Raymond James Financial', 'RJF'], 'RL': ['Ralph Lauren', 'RL'], 'RMD': ['ResMed', 'RMD', 'RSMDF'], 'ROK': ['Rockwell Automation', 'ROK'], 'ROL': ['Rollins', 'ROL'], 'ROP': ['Roper Technologies', 'ROP'], 'ROST': ['Ross Stores', 'ROST'], 'RSG': ['Republic Services', 'RSG'], 'RTX': ['Raytheon', 'RTX'], 'SBAC': ['SBA Communications', 'SBAC'], 'SBNY': ['Signature Bank', 'SBNY'], 'SBUX': ['Starbucks', 'SBUX'], 'SCHW': ['The Charles Schwab', 'SCHW'], 'SEDG': ['SolarEdge Technologies', 'SEDG'], 'SEE': ['Sealed Air', 'SEE'], 'SGEN': ['Seagen', 'SGEN'], 'SHW': ['The Sherwin-Williams', 'SHW'], 'SIRI': ['Sirius XM Holdings', 'SIRI'], 'SIVB': ['SVB Financial', 'SIVB'], 'SJM': ['The J. M. Smucker', 'SJM'], 'SLB': ['Schlumberger', 'SLB'], 'SNA': ['Snap-on', 'SNA'], 'SNPS': ['Synopsys', 'SNPS'], 'SO': ['Southern', 'SO'], 'SPG': ['Simon Property', 'SPG'], 'SPGI': ['S&P Global', 'SPGI'], 'SPLK': ['Splunk', 'SPLK'], 'SRE': ['Sempra Energy', 'SRE'], 'STE': ['STERIS', 'STE'], 'STT': ['State Street', 'STT'], 'STX': ['Seagate Technology', 'STX'], 'SWK': ['Stanley Black & Decker', 'SWK'], 'SWKS': ['Skyworks Solutions', 'SWKS'], 'SYF': ['Synchrony Financial', 'SYF'], 'SYK': ['Stryker', 'SYK'], 'SYY': ['Sys', 'SYY'], 'T': ['AT&T', 'T'], 'TAP': ['Molson Coors Beverage', 'TAP', 'TAP-A'], 'TDG': ['TransDigm', 'TDG'], 'TDY': ['Teledyne Technologies Incorporated', 'TDY'], 'TEAM': ['Atlassian', 'TEAM'], 'TECH': ['Bio-Techne', 'TECH'], 'TEL': ['TE Connectivity', 'TEL'], 'TER': ['Teradyne', 'TER'], 'TFC': ['Truist Financial', 'TFC'], 'TFX': ['Teleflex', 'TFX'], 'TGT': ['Target', 'TGT'], 'TJX': ['The TJX', 'TJX'], 'TMO': ['Thermo Fisher Scientific', 'TMO'], 'TMUS': ['T-Mobile US', 'TMUS'], 'TPR': ['Tapestry', 'TPR'], 'TRGP': ['Targa Resources Corp.', 'TRGP'], 'TRMB': ['Trimble', 'TRMB'], 'TROW': ['T. Rowe Price', 'TROW'], 'TRV': ['The Travelers', 'TRV'], 'TSCO': ['Tractor Supply', 'TSCO'], 'TSLA': ['Tesla', 'TSLA'], 'TSN': ['Tyson Foods', 'TSN'], 'TT': ['Trane Technologies', 'TT'], 'TTWO': ['Take-Two Interactive Software', 'TTWO'], 'TXN': ['Texas Instruments', 'TXN'], 'TXT': ['Textron', 'TXT'], 'TYL': ['Tyler Technologies', 'TYL'], 'UAL': ['United Continental Holdings', 'UAL'], 'UDR': ['UDR', 'UDR'], 'ULTA': ['Ulta Beauty', 'ULTA'], 'UNH': ['UnitedHealth', 'UNH'], 'UNP': ['Union Pacific', 'UNP'], 'UPS': ['United Parcel Service', 'UPS'], 'URI': ['United Rentals', 'URI'], 'USB': ['U.S. Bancorp', 'USB'], 'V': ['Visa', 'V'], 'VFC': ['V.F.', 'VFC'], 'VICI': ['Vici', 'VICI'], 'VLO': ['Valero Energy', 'VLO'], 'VMC': ['Vulcan Materials', 'VMC'], 'VNO': ['VornadoTrust', 'VNO', 'VNORP'], 'VRSK': ['Verisk Analytics', 'VRSK'], 'VRSN': ['VeriSign', 'VRSN'], 'VRTX': ['Vertex Pharmaceuticals', 'VRTX'], 'VTR': ['Ventas', 'VTR'], 'VTRS': ['Viatris', 'VTRS'], 'VZ': ['Verizon Communications', 'VZ'], 'WAB': ['Wabtec', 'WAB'], 'WAT': ['Waters', 'WAT'], 'WBA': ['Walgreens Boots Alliance', 'WBA'], 'WBD': ['Warner Bros. Discovery', 'WBD'], 'WDAY': ['Workday', 'WDAY'], 'WDC': ['Western Digital', 'WDC'], 'WEC': ['WEC Energy', 'WEC'], 'WELL': ['Welltower', 'WELL'], 'WFC': ['Wells Fargo &', 'WFC'], 'WHR': ['Whirlpool', 'WHR'], 'WM': ['Waste Management', 'WM'], 'WMB': ['The Williams', 'WMB'], 'WMT': ['Walmart', 'WMT'], 'WRB': ['W. R. Berkley', 'WRB'], 'WRK': ['WestRock', 'WRK'], 'WST': ['West Pharmaceutical Services', 'WST'], 'WY': ['Weyerhaeuser', 'WY'], 'WYNN': ['Wynn Resorts', 'WYNN'], 'XEL': ['Xcel Energy', 'XEL'], 'XRAY': ['Dentyply Sirona', 'XRAY'], 'XYL': ['Xylem', 'XYL'], 'YUM': ['YUM! Brands', 'YUM'], 'ZBH': ['Zimmer Biomet Holdings', 'ZBH'], 'ZBRA': ['Zebra Technologies', 'ZBRA'], 'ZION': ['Zions BanNational Association', 'ZION'], 'ZM': ['Zoom Video Communications', 'ZM'], 'ZS': ['Zscaler', 'ZS'], 'ZTS': ['Zoetis', 'ZTS'], 'FISV': ['Fiserv', 'FI', 'FISV'], 'FRCB': ['First Republic Bank', 'FRCB', 'FRC'], 'GOOG': ['Alphabet', 'GOOG', 'GOOGL'], 'HBAN': ['Huntington', 'Huntington Bancshares', 'HBAN', 'HBANN'], 'LHX': ['L3Harris', 'HRS', 'LHX'], 'IP': ['International Paper', 'INPAP', 'IP'], 'NEE': ['NextEra Energy', 'NEE', 'NEEXU'], 'O': ['Realty Income', 'Realty Income Corp', 'O'], 'UHT': ['Universal Health Realty', 'UHT'], 'PSKY': ['Paramount', 'Paramount Skydance', 'PARA', 'PARAA', 'PSKY'], 'RF': ['Regions Financial', 'RF', 'RF-PB'], 'UHS': ['Universal Health Services', 'UHID', 'UHS'], 'WTW': ['WTW Public', 'Willis Towers Watson', 'WTW', 'WLTW'], 'XOM': ['Exxon Mobil', 'XOM', 'XON'], 'GME': ['GME', 'GameStop'], 'AMC': ['AMC'], 'BB': ['BB', 'BlackBerry'], 'KOSS': ['KOSS', 'Koss'], 'NOK': ['NOK', 'Nokia'], 'EXPR': ['EXPR', 'Express'], 'SNDL': ['SNDL', 'SunDial'], 'BBBY': ['BBBY', 'Bed Bath Beyond', 'Bed Bath & Beyond'], 'PLTR': ['PLTR', 'Palantir'], 'CLOV': ['CLOV', 'Clover'], 'SPCE': ['SPCE', 'Virgin Galactic'], 'VIR': ['VIR'], 'FUBO': ['FUBO', 'Fubo', 'Fubotv'], 'BYND': ['BYND', 'Beyond'], 'WISH': ['WISH', 'ContextLogic'], 'CVNA': ['CVNA', 'Carvana'], 'UPST': ['UPST', 'Upstart'], 'QQQ': ['Nasdaq', 'NDAQ', 'QQQ', 'QQQM'], 'SPY': ['SPY', 'SPX', 'SP500', 'S&P500']}

In [ ]:
from tqdm.auto import tqdm
tqdm.pandas()

sep = r'(?:^|[\s.,;:!?()\[\]"\'])'
end_sep = r'(?=$|[\s.,;:!?()\[\]"\'])'
uppercase_only = [
  'ARE',
  'HAS',
  'IT',
  'NOW',
  'ON',
  'SEE',
  'LOW',
  'SO',
  'HES',
  'T',
  'FAST',
  'WISH',
  'SEE',
  'PPL',
  'ICE',
  'BEN',
  'K',
  'KIM',
  'DTE',
  'D',
  'KEYS',
  'COST',
  'POOL',
  'ALL',
  'WELL',
  'O',
]

ticker_patterns = {}
for ticker, names in associations.items():
  name_patterns = []
  for name in names:
    escaped = re.escape(name)
    if name.upper() in uppercase_only:
      name_patterns.append(escaped)
    else:
      name_patterns.append(f'(?i:{escaped})')
  pattern = sep + '(' + '|'.join(name_patterns) + ')' + end_sep
  ticker_patterns[ticker] = re.compile(pattern)

def find_tickers(text):
  mentioned = [ticker for ticker, pattern in ticker_patterns.items() if pattern.search(text)]
  return mentioned

df_sample = df.head(100)
df_sample['mentioned_tickers'] = df_sample['text'].progress_apply(find_tickers)

/Users/OwenScott/.pyenv/versions/3.13.5/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
100%|██████████| 100/100 [00:01<00:00, 89.02it/s]
/var/folders/2s/vhdt8ph920d695tdxy4n9w9h0000gn/T/ipykernel_27887/3026086501.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sample['mentioned_tickers'] = df_sample['text'].progress_apply(find_tickers)

In [13]:
df['mentioned_tickers'] = df['text'].progress_apply(find_tickers)

100%|██████████| 53183/53183 [07:29<00:00, 118.44it/s]

In [14]:
df = df[df['mentioned_tickers'].map(len) > 0]
print(len(df))
df.head()

30904

,eastern,text,mentioned_tickers
1,2021-01-28 06:32:10-05:00,Math Professor Scott Steiner says the numbers ...,[GME]
2,2021-01-28 06:30:35-05:00,Exit the system The CEO of NASDAQ pushed to ha...,"[GME, QQQ]"
3,2021-01-28 06:28:57-05:00,NEW SEC FILING FOR GME! CAN SOMEONE LESS RETAR...,[GME]
4,2021-01-28 06:26:56-05:00,"Not to distract from GME, just thought our AMC...","[GME, AMC]"
6,2021-01-28 06:26:27-05:00,SHORT STOCK DOESN'T HAVE AN EXPIRATION DATE He...,[T]

In [16]:
df.to_parquet('../data/reddit_wsb_cache.parquet', engine='pyarrow', compression='gzip')